apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: escuela

namePrefix: dev-

commonLabels:
  environment: development
  team: tita-group

replicas:
  - name: eureka-server
    count: 1
  - name: api-gateway
    count: 2
  - name: ms-auth
    count: 1
  - name: ms-estudiantes
    count: 1
  - name: ms-instructores
    count: 1
  - name: ms-vehiculos
    count: 1
  - name: ms-asignaciones
    count: 1
  - name: ms-cobros
    count: 1
  - name: ms-reportes
    count: 1
  - name: ms-notificaciones
    count: 1

resources:
  - namespace-patch.yml
