apiVersion: v1
kind: Namespace
metadata:
  name: proyecto-titulacion
  labels:
    name: proyecto-titulacion
    app.kubernetes.io/name: proyecto-titulacion
    app.kubernetes.io/part-of: proyecto-titulacion
