apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: escuela

resources:
  - namespace.yml
  - postgres.yml
  - rabbitmq.yml
  - eureka-server.yml
  - api-gateway.yml
  - ms-auth.yml
  - ms-estudiantes.yml

commonLabels:
  app.kubernetes.io/managed-by: argocd
  project: proyecto-titulacion
