apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: escuela-conduccion
spec:
  ports:
    - port: 5672
      targetPort: 5672
      name: amqp
    - port: 15672
      targetPort: 15672
      name: management
  clusterIP: None
  selector:
    app: rabbitmq
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: escuela-conduccion
spec:
  serviceName: rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.12-management-alpine
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef: { name: rabbitmq-secrets, key: RABBITMQ_DEFAULT_USER }
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef: { name: rabbitmq-secrets, key: RABBITMQ_DEFAULT_PASS }
          volumeMounts:
            - name: data
              mountPath: /var/lib/rabbitmq
          readinessProbe:
            exec: { command: ["rabbitmq-diagnostics", "ping"] }
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            exec: { command: ["rabbitmq-diagnostics", "status"] }
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
