apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proyecto-titulacion
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Kynsofttita-com/proyecto-titulacion-udla.git
    targetRevision: main
    path: kubernetes/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: escuela

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10
