apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proyecto-titulacion
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Kynsofttita-com/proyecto-titulacion-udla.git
    targetRevision: main
    path: kubernetes/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: escuela

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
