apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: escuela

resources:
  - namespace.yml
  - postgres.yml
  - rabbitmq.yml
  - minio.yml
  - eureka.yml
  - api-gateway.yml

replicas:
  - name: api-gateway
    count: 1
