apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  labels:
    app: proyecto-titulacion
type: Opaque
stringData:
  username: "escuela_user"
  password: "changeme"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  labels:
    app: proyecto-titulacion
type: Opaque
stringData:
  username: "guest"
  password: "guest"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  labels:
    app: proyecto-titulacion
type: Opaque
stringData:
  secret: "my-256-bit-secret-key-for-jwt-signing-algorithm-HS512-implementation-12345678901234567890"
